routes/web.php
<?php
Route::post('formSubmit','PostController@formSubmit');



Auth::routes(['verify' => true]);

Route::get('/', function () {
    return redirect()->route('home');
});

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);

//Группа для авторизованных пользователей
Route::group(['prefix' => 'auth', 'middleware' => ['auth']], function () {



    Route::get('/testpage', ['as' => 'testpage', 'uses' => 'HomeController@testpage']);

    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     *
     * users\ProfileController   Контроллер профилей
     *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    Route::resource('profiles', 'users\ProfileController');
    Route::get('/profiles/index/{id}/{method?}', ['as' => 'profiles.index', 'uses' => 'users\ProfileController@index']);
    Route::get('/profiles/create/{id}', ['as' => 'profiles.create', 'uses' => 'users\ProfileController@create']);




});

//Группа для пользователей, которые подтвердили свою почту
Route::group(['prefix' => 'verified', 'middleware' => ['verified']], function () {


    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    *
    * users\MessageController   Контроллер сообщений ? Ajax поиски
    *
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    Route::get('/messages/ajax_find_users_to_message', ['as' => 'ajax_find_users_to_message', 'uses' => 'users\MessageController@ajax_find_users_to_message']);



    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     *
     * users\MessageController   Контроллер сообщений
     *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    Route::resource('messages', 'users\MessageController');
    Route::get('/messages/index/{user_id}/{kind_of?}', ['as' => 'messages.index', 'uses' => 'users\MessageController@index']);
    Route::get('/messages/read/{message_id}/{confirm?}', ['as' => 'messages.read', 'uses' => 'users\MessageController@read']);


    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
       *
       * Api\ApiMessageController   Контроллер сообщений для vue.js возвращает json todo это рабочий был VueMessageController
       *
       * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    Route::get('vue/messages/index/{user_id}/{kind_of?}', ['as' => 'vue.messages.index', 'uses' => 'Api\ApiMessageController@index']);
    Route::get('vue/messages/read/{message_id}/{first_time_read?}', ['as' => 'vue.messages.read', 'uses' => 'Api\ApiMessageController@read']);

    Route::post('vue/messages/search_users', ['as' => 'vue.messages.search_users', 'uses' => 'Api\ApiMessageController@search_users']);
    Route::post('vue/messages/store', ['as' => 'vue.messages.store', 'uses' => 'Api\ApiMessageController@store']);

});


//Группа для владельца
Route::group(['prefix' => 'owner', 'middleware' => ['role:owner']], function () {
    Route::get('/testpage', ['as' => 'testpage2', 'uses' => 'HomeController@testpage']);

    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
     *
     * Owner\OwnerController   Контроллер владельца
     *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
    Route::get('/all_users', ['as' => 'all_users', 'uses' => 'Owner\OwnerController@all_users']);

    Route::get('/change_role/{user_id}/{role_id}/{current_page}', ['as' => 'change_role', 'uses' => 'Owner\OwnerController@change_role']);
});






//Группа для админов
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('/testpage', ['as' => 'testpage3', 'uses' => 'HomeController@testpage']);
});

//Группа для модераторов
Route::group(['prefix' => 'moder', 'middleware' => ['role:moder']], function () {
    Route::get('/testpage', ['as' => 'testpage4', 'uses' => 'HomeController@testpage']);
});

//Группа для юзеров
Route::group(['prefix' => 'user', 'middleware' => ['role:user']], function () {
    Route::get('/testpage', ['as' => 'testpage5', 'uses' => 'HomeController@testpage']);
});

app/Models/Users/Profile.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{

    //Теперь примари кеем будет это значение
    protected $primaryKey = 'user_id';


    protected $fillable = [
        'user_id', 'first_name', 'last_name', 'second_name', 'phone'
    ];
}

app/Http/Controllers/Users/ProfileController.php
<?php

namespace App\Http\Controllers\Users;

use Illuminate\Support\Facades\View;
use App\Models\Users\Profile;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');

        $bom = 'test';
        // Sharing is caring
        View::share('test', $bom);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id, $method = 'show')
    {
        if ($method == 'show') {
            $data['title'] = 'Профиль';
        } elseif ($method == 'create') {
            $data['title'] = 'Создание профиля';
        } elseif ($method == 'edit') {
            $data['title'] = 'Изменение профиля';
        }
        $cheked_user = Auth::user();
        $checked_user_id = $cheked_user->id;
        $data['user'] = $user = User::find($id);
        //В зависимости от метода возвращаются разные формы, просмотра, создания или удаления
        $data['method'] = $method;
        if ($id == $checked_user_id || $cheked_user->inRole(1)) {
            // 4 varables true or false = $is_owner $is_admin $is_moder $is_user
            $data = array_merge($data, $user->getRoleVariables());

            $data['profile'] = Profile::where('user_id', $id)->first();

            return view('profiles.index', $data);

        } else {
            return back()->with('error', 'Доступ закрыт');
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {

        $method = 'create';
        $profile = Profile::where('user_id', $id)->first();
        if (is_null($profile)) {
            return redirect()->route('profiles.index', [$id, $method]);
        } else {
            return back()->with('error', 'Данные профиля уже заполнены');
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request = $request->all();
        $user_id = $request['user_id'];


        if(!isset($request['agree']) || !$request['agree'])
            return back()->withInput()->with('error','Вы не согласились на обработку данных');

        $profile = Profile::where('user_id',$user_id)->first();
        if (is_null($profile)){
            $profile = Profile::create($request);

            $method = 'show';
            return redirect()->route('profiles.index', [$user_id, $method])->with('success','Профиль создан');


        }else{
            return back()->with('error','Профиль уже создан, проверьте исправность мыши, так как возможно вы кликнули 2 раза');
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\Users\Profile $profile
     * @return \Illuminate\Http\Response
     */
    public function show(Profile $profile)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Users\Profile $profile
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $method = 'edit';
        $profile = Profile::where('user_id', $id)->first();
        if (!is_null($profile)) {
            return redirect()->route('profiles.index', [$id, $method]);
        } else {
            return back()->with('error', 'Профиля еще нет, создайте');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\models\Users\Profile $profile
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        //todo сделать серверный валидатор на заполнение форм.
        $request = $request->all();

        if(!isset($request['agree']) || !$request['agree'])
            return back()->withInput()->with('error','Вы не согласились на обработку данных');

        $profile = Profile::where('user_id',$id)->first()->update($request);
        $method = 'show';
        return redirect()->route('profiles.index', [$id, $method])->with('success','Профиль изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Users\Profile $profile
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/profiles/includes/create.blade.php
{!! Form::open(['route' => ['profiles.store'], 'class' => 'needs-validation',  'novalidate']) !!}
{!! Form::hidden("user_id",$user->id) !!}

<div class="form-group">
    {!! Form::label('first_name', 'Имя:') !!}
    {{--Образец для валидации--}}
    {{--{!! Form::text('first_name', null, ['class' => 'form-control form-control-sm','required']) !!}--}}
    {{--<div class="invalid-feedback">Обязательное для заполнения</div>--}}

    {!! Form::text('first_name', null, ['class' => 'form-control form-control-sm']) !!}

</div>


<div class="form-group">
    {!! Form::label('last_name', 'Фамилия:') !!}
    {!! Form::text('last_name', null, ['class' => 'form-control form-control-sm']) !!}

</div>

<div class="form-group">
    {!! Form::label('second_name', 'Отчество:') !!}
    {!! Form::text('second_name', null, ['class' => 'form-control form-control-sm']) !!}

</div>

<div class="form-group">
    {!! Form::label('phone', 'Телефон:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control form-control-sm']) !!}
</div>



<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" value="true" name="agree"
               id="agree">
        <label class="custom-control-label" for="agree"> Согласен на обработку персональных данных</label>
    </div>
</div>
<br>

{!! Form::submit( 'Создать',  ["class" =>  "btn btn-success btn-block"]) !!}
{!! Form::close() !!}

resources/views/profiles/includes/edit.blade.php
{!! Form::open(['route' => ['profiles.update',$user->id], 'class' => 'needs-validation',  'novalidate','method' => 'PUT']) !!}

<div class="form-group">
    {!! Form::label('first_name', 'Имя:') !!}
    {{--Образец для валидации--}}
    {{--{!! Form::text('first_name', null, ['class' => 'form-control form-control-sm','required']) !!}--}}
    {{--<div class="invalid-feedback">Обязательное для заполнения</div>--}}

    {!! Form::text('first_name', $profile->first_name, ['class' => 'form-control form-control-sm']) !!}

</div>


<div class="form-group">
    {!! Form::label('last_name', 'Фамилия:') !!}
    {!! Form::text('last_name', $profile->last_name, ['class' => 'form-control form-control-sm']) !!}

</div>

<div class="form-group">
    {!! Form::label('second_name', 'Отчество:') !!}
    {!! Form::text('second_name', $profile->second_name, ['class' => 'form-control form-control-sm']) !!}

</div>

<div class="form-group">
    {!! Form::label('phone', 'Телефон:') !!}
    {!! Form::text('phone', $profile->phone, ['class' => 'form-control form-control-sm']) !!}
</div>


<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" value="true" name="agree"
               id="agree">
        <label class="custom-control-label" for="agree"> Согласен на обработку персональных данных</label>
    </div>
</div>

<br>
{!! Form::submit( 'Редактировать',  ["class" =>  "btn btn-success btn-block"]) !!}
{!! Form::close() !!}

resources/views/profiles/includes/show.blade.php
@if(is_null($profile))
    <div class="row bg-light-dim br-3 hoverer mt-1 mb-1">
        <div class="col-12 font-weight-bold ">
            Данные профиля еще не заполнены
        </div>
    </div>
    <div class="row bg-light-dim br-3 mt-1 mb-1">
        <a class="btn btn-success btn-block"
           href="{{route('profiles.create',$user->id)}}">Заполнить данные профиля</a>
    </div>
@else
    <div class="row bg-light-dim br-3 hoverer mt-1 mb-1">
        <div class="col-12 col-lg-4 font-weight-bold ">
            Имя:
        </div>
        <div class="col-12 col-lg-8  ">
            {{$profile->first_name}}
        </div>
    </div>

    <div class="row bg-light-dim br-3 hoverer mt-1 mb-1">
        <div class="col-12 col-lg-4 font-weight-bold ">
            Фамилия:
        </div>
        <div class="col-12 col-lg-8  ">
            {{$profile->last_name}}
        </div>
    </div>

    <div class="row bg-light-dim br-3 hoverer mt-1 mb-1">
        <div class="col-12 col-lg-4 font-weight-bold ">
            Отчество:
        </div>
        <div class="col-12 col-lg-8  ">
            {{$profile->second_name}}
        </div>
    </div>

    <div class="row bg-light-dim br-3 hoverer mt-1 mb-1">
        <div class="col-12 col-lg-4 font-weight-bold ">
            Телефон:
        </div>
        <div class="col-12 col-lg-8  ">
            {{$profile->phone}}
        </div>
    </div>

    <br>
    <div class="row bg-light-dim br-3 mt-1 mb-1">
        <a class="btn btn-info btn-block"
           href="{{route('profiles.edit',$user->id)}}">Редактировать данные профиля</a>
    </div>

@endif